apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  replicas: 1 
  minReadySeconds: 45
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
      - image: 4544927/exchange-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: exchange-service
        ports:
        - name: liveness-port
          containerPort: 8000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  ports:
  - # nodePort: 30702 
    port: 8000 
    protocol: TCP
    targetPort: 8000 
  selector:
    app: exchange-service
  sessionAffinity: None 
  type: LoadBalancer